title: "<span style='color: #171717; font-size: 1em;'>Title..</span><span style='color: #E9EAEC; font-size: .5em;'>Blog about software dvelopment</span>"
baseurl: ""

font: 'Roboto'
font_weights:
  regular: 400
  bold: 700

